-- Active: 1777485633252@@127.0.0.1@5432@library@public
INSERT INTO  category (ID, DESCRIPTION) VALUES (1, 'Eletrônicos');
INSERT INTO  category (ID, DESCRIPTION) VALUES (2, 'Livros');
INSERT INTO  category (ID, DESCRIPTION) VALUES (3, 'Computadores');

INSERT INTO SUPPLIER (ID, NAME) VALUES (1, 'Amazon');
INSERT INTO SUPPLIER (ID, NAME) VALUES (2, 'Curitiba Books');

INSERT INTO PRODUCT (ID, NAME, STOQUE, FK_CATEGORY, FK_SUPPLIER) VALUES (1, 'Smart TV', 15, 1, 1);
INSERT INTO PRODUCT (ID, NAME, STOQUE, FK_CATEGORY, FK_SUPPLIER) VALUES (2, 'Macbook Pro', 10, 3, 1);
INSERT INTO PRODUCT (ID, NAME, STOQUE, FK_CATEGORY, FK_SUPPLIER) VALUES (3, 'The Lord of the Rings', 22, 2, 2);